#!/usr/bin/env python3
"""Resize, crop and encode the magazine photos.

Reads scripts/images.json, writes assets/img/magazine/<slug>-<w>.{jpg,webp}
and _data/images.yml (manifest used by the Jekyll includes).
Run:  python3 scripts/build_images.py
Deps: pillow
"""
import base64, io, json, os, sys
from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
cfg = json.loads((ROOT / "scripts/images.json").read_text())
out = ROOT / cfg["outDir"]; out.mkdir(parents=True, exist_ok=True)
src_dir = ROOT / cfg["srcDir"]

def crop_to_aspect(im, aspect, focal):
    aw, ah = (int(x) for x in aspect.split(":"))
    W, H = im.size
    target = aw / ah
    if W / H > target:            # too wide -> trim width
        nw, nh = int(round(H * target)), H
    else:                         # too tall -> trim height
        nw, nh = W, int(round(W / target))
    fx, fy = focal[0] / 100, focal[1] / 100
    left = min(max(int(W * fx - nw / 2), 0), W - nw)
    top = min(max(int(H * fy - nh / 2), 0), H - nh)
    return im.crop((left, top, left + nw, top + nh))

manifest = {}
for slug, spec in cfg["images"].items():
    im = ImageOps.exif_transpose(Image.open(src_dir / spec["src"])).convert("RGB")
    im = crop_to_aspect(im, spec["aspect"], spec["focal"])
    W, H = im.size
    sizes = []
    for w in spec["widths"]:
        w = min(w, W)                        # never upscale
        h = int(round(H * w / W))
        r = im.resize((w, h), Image.LANCZOS)
        jpg = out / f"{slug}-{w}.jpg"; webp = out / f"{slug}-{w}.webp"
        r.save(jpg, "JPEG", quality=82, optimize=True, progressive=True)
        r.save(webp, "WEBP", quality=80, method=6)
        sizes.append({"w": w, "h": h})
    sizes = [dict(t) for t in {tuple(s.items()) for s in sizes}]   # dedupe capped widths
    sizes.sort(key=lambda s: s["w"])
    tiny = im.resize((24, int(round(24 * H / W))), Image.LANCZOS)
    buf = io.BytesIO(); tiny.save(buf, "WEBP", quality=40)
    manifest[slug] = {
        "alt": spec["alt"], "credit": spec["credit"], "aspect": spec["aspect"],
        "width": sizes[-1]["w"], "height": sizes[-1]["h"], "source": spec["src"],
        "sizes": [s["w"] for s in sizes],
        "lqip": "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode(),
    }
    print(f"{slug:24s} {spec['src'][:38]:40s} crop {W}x{H} -> {[s['w'] for s in sizes]}")

(ROOT / "_data").mkdir(exist_ok=True)
with open(ROOT / "_data/images.yml", "w") as f:
    f.write("# Generated by scripts/build_images.py — do not edit by hand.\n")
    for slug, m in manifest.items():
        f.write(f"{slug}:\n")
        for k, v in m.items():
            if isinstance(v, list):
                f.write(f"  {k}: [{', '.join(str(x) for x in v)}]\n")
            else:
                f.write(f"  {k}: {json.dumps(v)}\n")
print("wrote _data/images.yml with", len(manifest), "entries")
